#!/usr/bin/env python3
"""Generate small, independently replayable search trees for Dirac60.

Each certificate proves that a list-colouring instance has no proper
3-colouring.  The checker used in Lean does not trust the search procedure:
at a branch it recomputes which colours are still possible, and it insists
on a valid child for every possible colour.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json

EDGE_FILE = Path(__file__).with_name("candidate60.edgelist")
OUT_JSON = Path(__file__).with_name("certificates.json")
OUT_LEAN = Path(__file__).with_name("Dirac60Certificates.lean")
N = 60
ALL = 0b111


def read_edges() -> tuple[list[tuple[int, int]], list[int]]:
    edges: list[tuple[int, int]] = []
    adj = [0] * N
    for raw in EDGE_FILE.read_text().splitlines():
        a, b = map(int, raw.split())
        assert 0 <= a < b < N
        edges.append((a, b))
        adj[a] |= 1 << b
        adj[b] |= 1 << a
    assert len(edges) == 180 and all(x.bit_count() == 6 for x in adj)
    return edges, adj


@dataclass(frozen=True)
class Node:
    vertex: int
    children: tuple[int, int, int]  # -1 exactly when that colour is disallowed


class Search:
    def __init__(self, adj: list[int], active: int, masks: list[int]):
        self.adj = adj
        self.active = active
        self.masks = masks
        self.nodes: list[Node] = []

    def allowed(self, v: int, k: int, assigned: tuple[int, ...]) -> bool:
        if not (self.masks[v] & (1 << k)):
            return False
        z = self.adj[v] & self.active
        while z:
            bit = z & -z
            w = bit.bit_length() - 1
            z ^= bit
            if assigned[w] == k:
                return False
        return True

    def choose(self, assigned: tuple[int, ...]) -> tuple[int, list[int]]:
        best_v = -1
        best_options: list[int] = []
        best_key = (4, 0, 0)
        z = self.active
        while z:
            bit = z & -z
            v = bit.bit_length() - 1
            z ^= bit
            if assigned[v] >= 0:
                continue
            opts = [k for k in range(3) if self.allowed(v, k, assigned)]
            coloured_neighbours = 0
            q = self.adj[v] & self.active
            while q:
                b = q & -q
                w = b.bit_length() - 1
                q ^= b
                coloured_neighbours += assigned[w] >= 0
            # Fewest options, then most coloured neighbours, then higher degree.
            key = (len(opts), -coloured_neighbours, -(self.adj[v] & self.active).bit_count())
            if best_v < 0 or key < best_key:
                best_v, best_options, best_key = v, opts, key
                if not opts:
                    break
        return best_v, best_options

    def build(self, assigned: tuple[int, ...]) -> int:
        v, options = self.choose(assigned)
        if v < 0:
            raise RuntimeError("instance unexpectedly has a colouring")
        children = [-1, -1, -1]
        for k in options:
            nxt = list(assigned)
            nxt[v] = k
            children[k] = self.build(tuple(nxt))
        idx = len(self.nodes)
        self.nodes.append(Node(v, tuple(children)))
        return idx

    def run(self) -> int:
        return self.build(tuple([-1] * N))


def emit_lean(cases: list[dict]) -> None:
    lines = [
        "/- This file is generated by generate_certificates.py. -/",
        "import Dirac60",
        "",
        "namespace Dirac60",
        "",
        "set_option maxHeartbeats 0",
        "set_option maxRecDepth 1000000",
        "",
    ]
    for case in cases:
        name = case["name"]
        nodes = case["nodes"]

        def tree(index: int) -> str:
            if index < 0:
                return ".closed"
            node = nodes[index]
            a, b, c = (tree(x) for x in node["children"])
            return f"(.branch {node['vertex']} {a} {b} {c})"

        lines.append(f"def {name}Cert : SearchTree :=")
        lines.append("  " + tree(case["root"]))
        lines.append("")
    lines.append("end Dirac60")
    OUT_LEAN.write_text("\n".join(lines) + "\n")


def main() -> None:
    _, adj = read_edges()
    root = 0
    neighbours = [v for v in range(N) if (adj[root] >> v) & 1]
    assert neighbours == [5, 26, 30, 33, 37, 55]
    active = ((1 << N) - 1) ^ (1 << root)
    cases: list[dict] = []
    for si, s in enumerate(neighbours):
        for colour in range(3):
            masks = [ALL] * N
            masks[root] = 0
            masks[s] = 1 << colour
            for t in neighbours:
                if t != s:
                    masks[t] &= ~(1 << colour)
            search = Search(adj, active, masks)
            cert_root = search.run()
            name = f"dupFail_s{si}_c{colour}"
            cases.append({
                "name": name,
                "kind": "unique",
                "neighbour": s,
                "colour": colour,
                "masks": masks,
                "root": cert_root,
                "nodes": [
                    {"vertex": n.vertex, "children": list(n.children)}
                    for n in search.nodes
                ],
            })
            print(name, len(search.nodes))
    # These three instances rule out a colour missing entirely from N(0).
    # Together with the 18 no-unique-colour instances and |N(0)| = 6, they
    # certify the exact 2+2+2 profile without fixing colour names.
    for colour in range(3):
        masks = [ALL] * N
        masks[root] = 0
        for t in neighbours:
            masks[t] &= ~(1 << colour)
        search = Search(adj, active, masks)
        cert_root = search.run()
        name = f"missing_c{colour}"
        cases.append({
            "name": name,
            "kind": "missing",
            "colour": colour,
            "masks": masks,
            "root": cert_root,
            "nodes": [
                {"vertex": n.vertex, "children": list(n.children)}
                for n in search.nodes
            ],
        })
        print(name, len(search.nodes))
    OUT_JSON.write_text(json.dumps({"cases": cases}, separators=(",", ":")))
    emit_lean(cases)
    print("total nodes", sum(len(c["nodes"]) for c in cases))


if __name__ == "__main__":
    main()
